### ISSUE TITLE
Remaining `wepoll` items.

### ISSUE THREAD

**Issue by carllerche** [tokio-rs/mio#1041]
Meta issue tracking remaining work to do on the `wepoll` windows implementation. This description will be updated over time.

Original PR: #1034. Original issue #1024.

- [x] Dealing with `WSAStartup`, #1046. (solved in #1029)
- [ ] benchmark new implementation vs. old.
- [x] ensure wepoll licensing requirements are met (copy license file).
- [ ] code comment ownership of pointers being passed around the system.
- [ ] ensure memory is not leaked on error [here](https://github.com/tokio-rs/mio/blob/65f19ddcb3ac554c23b0c3fa0665e64ff80141f1/src/sys/windows/afd.rs#L159).
- [ ] Ensure all old Windows related issues are fixed with the new implementation.
- [ ] Ability to add custom IOCP handler #1047.
- [ ] Document interaction with `RawSocket` (do not read / write directly).
- [ ] Concurrent polling & registering, see #1053.
- [ ] Find source of possible polling delay, see https://github.com/tokio-rs/mio/pull/1051#issuecomment-522232178.
- [ ] Fix issues found by additional tests added in #1070:
  - [x] #1073.
  - [ ] #1074.
  - [x] #1078.
  - [x] #1079.
  - [x] #1080.

**Comment by Thomasdezeeuw** [comment]
- [ ] Ensure all old Windows related issues are fixed with the new implementation.

**Comment by carllerche** [comment]
@Thomasdezeeuw I added your item to the OP. Do you have permission to edit the OP directly?

**Comment by Thomasdezeeuw** [comment]
Yes, but didn't know that.

**Comment by carllerche** [comment]
@Thomasdezeeuw no worries 👍

**Comment by PerfectLaugh** [comment]
about memory leak on #1042

**Comment by PerfectLaugh** [comment]
And we probably need to make a notice that the socket can NEVER be used in other place simultaneously with Mio. Because we simulated ET behavior by intercepting all operations that users could do.
If they use the socket in the place where Mio cannot observe (like RawSocket), the polling behavior will be undefined.

**Comment by piscisaureus** [comment]
I would like to add: the current locking scheme is too granular.

It makes little sense to use separate locks for the update_queue and the iocp HANDLE; it's likely to hurt performance and introduce subtle bugs. One example I could find:

https://github.com/tokio-rs/mio/blob/211223e92865e5ae276333cc91673d764bbc386d/src/sys/windows/selector.rs#L368-L370
```rust
        self.update_sockets_events()?;

        self.active_poll_count.fetch_add(1, Ordering::SeqCst);
```

^-- By calling `update_socket_events()` before incrementing `active_poll_count`, it's possible that another thread doesn't call `update_socket_events()` (because it looks like there are no active polls) when it should (because there actually is another thread that's about to block).

This is just an example, which could be easily fixed by reversing the two operations. But in general I think it'd be better to use a single lock to protect both the completion port *and* the associated state. Then you release this lock just before calling `GetQueuedCompletionStatusEx()` and immediately acquire it again right after `GetQueuedCompletionStatusEx()` returns.

This might require integrating parts of miow into mio, which seems like a good idea either way.

**Comment by PerfectLaugh** [comment]
> I would like to add: the current locking scheme is too granular.
> 
> It makes little sense to use separate locks for the update_queue and the iocp HANDLE; it's likely to hurt performance and introduce subtle bugs. One example I could find:
> 
> https://github.com/tokio-rs/mio/blob/211223e92865e5ae276333cc91673d764bbc386d/src/sys/windows/selector.rs#L368-L370
> 
> ```rust
>         self.update_sockets_events()?;
> 
>         self.active_poll_count.fetch_add(1, Ordering::SeqCst);
> ```
> 
> ^-- By calling `update_socket_events()` before incrementing `active_poll_count`, it's possible that another thread doesn't call `update_socket_events()` (because it looks like there are no active polls) when it should (because there actually is another thread that's about to block).
> 
> This is just an example, which could be easily fixed by reversing the two operations. But in general I think it'd be better to use a single lock to protect both the completion port _and_ the associated state. Then you release this lock just before calling `GetQueuedCompletionStatusEx()` and immediately acquire it again right after `GetQueuedCompletionStatusEx()` returns.
> 
> This might require integrating parts of miow into mio, which seems like a good idea either way.

Is the pull #1055 making sense to you now?

**Comment by dtacalau** [comment]
@Thomasdezeeuw I'll start working on this issue, please assign it to me.

**Comment by dtacalau** [comment]
Update of what has been done so far: all items which are commented out are resolved.

//Dealing with WSAStartup, #1046. (solved in #1029)
 benchmark new implementation vs. old. //TODO
 ensure wepoll licensing requirements are met (copy license file). //TODO
 document ownership of pointers being passed around the system. //TODO
 ensure memory is not leaked on error here. //WIP
//Ensure all old Windows related issues are fixed with the new implementation.
 A SourceFd (EventedFd) equivalent for Windows. //TODO
 Document interaction with RawSocket (do not read / write directly). //TODO
 Concurrent polling & registering, see #1053 .//TODO
 Find source of possible polling delay, see #1051 (comment). //TODO
// Fix issues found by additional tests added in #1070:
// #1073.
 #1074. - //WIP
// #1078.
// #1079.
// #1080.

**Comment by dtacalau** [comment]
//Dealing with WSAStartup, #1046. (solved in #1029)
//benchmark new implementation vs. old.  https://github.com/tokio-rs/tokio/issues/1918
//TODO: Mio will be benchmarked through Tokio. Will open a Tokio issue to create a benchmark.
//ensure wepoll licensing requirements are met (copy license file). #1188
//document ownership of pointers being passed around the system. #1185
//ensure memory is not leaked on error here. #1190
//Ensure all old Windows related issues are fixed with the new implementation.
// A SourceFd (EventedFd) equivalent for Windows. #1187 
//Document interaction with RawSocket (do not read / write directly). #1186 
//Concurrent polling & registering, see #1053 .
//Find source of possible polling delay, see #1051 (comment). #1189 
// Fix issues found by additional tests added in #1070:
// #1073.
// #1074.
// #1078.
// #1079.
// #1080.

**Comment by dtacalau** [comment]
@Thomasdezeeuw this issue can be closed. All items have either been resolved or are tracked by other opened issues.
