### ISSUE TITLE
Follow up to switch to windows-sys

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1558]
Based on https://github.com/tokio-rs/mio/pull/1556, in particular this comment: https://github.com/tokio-rs/mio/pull/1556#pullrequestreview-920136232.

 * [x] Move the `SIO_BSP_*` constants, https://github.com/microsoft/win32metadata/issues/844.
 * [ ] ~~Replace `Handle` with [`std::os::windows::io::OwnedHandle`](https://doc.rust-lang.org/std/os/windows/io/struct.OwnedHandle.html) (once stable).~~ Tracked in https://github.com/tokio-rs/mio/issues/1588.
 * [x] Remove the feature for `AF_INET(6)` constants, see https://github.com/microsoft/win32metadata/issues/845.
 * [ ] AFD related types:
   * [ ] [`AfdPollHandleInfo`](https://github.com/tokio-rs/mio/blob/add08718543f50a27e802aa4c3ef3a4153d6d99c/src/sys/windows/afd.rs#L38-L44)
   * [ ] [`AfdPollInfo`](https://github.com/tokio-rs/mio/blob/add08718543f50a27e802aa4c3ef3a4153d6d99c/src/sys/windows/afd.rs#L48-L55)
   * [ ] [`POLL_` constants](https://github.com/tokio-rs/mio/blob/add08718543f50a27e802aa4c3ef3a4153d6d99c/src/sys/windows/afd.rs#L235-L255)

**Comment by kennykerr** [comment]
These fixes have now been published as part of the 0.35.0 release:

https://github.com/microsoft/windows-rs/releases/tag/0.35.0

**Comment by Thomasdezeeuw** [comment]
This https://github.com/microsoft/windows-rs/pull/1636 might be a bit of problem, as Mio supports older rustc versions. Does windows-sys give any MSRV guarantees?

**Comment by kennykerr** [comment]
It's currently set to 1.56:

https://github.com/microsoft/windows-rs/blob/d3c2f2ca9385a0f03162e33da40dcc350678161d/.github/workflows/build.yml#L52

Previously it was set to 1.46.0, which should still work in theory but cargo doesn't like it when the version is older than what Rust 2021 supports.

**Comment by Thomasdezeeuw** [comment]
This issue is now blocked on https://github.com/tokio-rs/mio/issues/1562.

**Comment by kennykerr** [comment]
[0.36.0](https://github.com/microsoft/windows-rs/releases/tag/0.36.0) has been released and [reverts the Rust 2021](https://github.com/microsoft/windows-rs/pull/1706) adoption meaning that `windows-sys` is once again supported on Rust 1.46.

**Comment by Thomasdezeeuw** [comment]
Updating to 0.36 in https://github.com/tokio-rs/mio/pull/1569.

I couldn't find the `SIO_BSP_*` constants although the linked issue is closed, have those been added @kennykerr?

**Comment by Thomasdezeeuw** [comment]
> > I couldn't find the `SIO_BSP_*` constants although the linked issue is closed, have those been added?
> 
> Which one in particular? I see a bunch have been added.

I just realised GitHub doesn't have partial search, window-sys actually has all the constants Mio need. Sorry about that

**Comment by Thomasdezeeuw** [comment]
Closing this as done, we can switch to using AFD constants from windows-sys if/when those become available, no point in keeping this open.

**Comment by riverar** [comment]
Happy to add those now; just need a pointer to what's missing/needed. Is it just the `POLL_xxx` constants linked above?

**Comment by riverar** [comment]
Ah, I see the others. Will be interesting to get these into metadata, given they're undocumented/"private" structures. 

```
//
// Structures for IOCTL_AFD_POLL.
//

typedef struct _AFD_POLL_HANDLE_INFO {
    HANDLE Handle;
    ULONG PollEvents;
    NTSTATUS Status;
} AFD_POLL_HANDLE_INFO, *PAFD_POLL_HANDLE_INFO;

typedef struct _AFD_POLL_INFO {
    LARGE_INTEGER Timeout;
    ULONG NumberOfHandles;
    BOOLEAN Unique;
    AFD_POLL_HANDLE_INFO Handles[1];
} AFD_POLL_INFO, *PAFD_POLL_INFO;
```

**Comment by Thomasdezeeuw** [comment]
> Ah, I see the others. Will be interesting to get these into metadata, given they're undocumented/"private" structures.

I suspected as much. I'm happy to keep the definitions in Mio as well.
